"""Align the schema with the models (server defaults + indexes/constraints).

Migrations 0001–0018 drifted from the ORM models in two ways, both surfaced by
`alembic check`:

1. Server defaults the DB carries but the models never declare. The models use
   Python-side ``default=`` (uuid4, 0, False, "INR", enum members, ``{}``/``[]``)
   for these columns, not ``server_default=``, so this migration strips the
   surplus DB-side defaults. Columns that legitimately declare ``server_default``
   in the model (created_at/updated_at, most enum status columns, CMS/HR/OTP/
   inventory flags, reviews.is_verified_purchase) are left untouched.

2. Redundant unique *constraints* (``uq_*``) on columns declared
   ``unique=True, index=True`` — the model expects only the unique *index*
   (``ix_*``), which already exists, so the constraint is dropped (uniqueness
   stays enforced by the index).

Real invariant / helper indexes the DB carries (``uq_product_prices_active``,
``uq_sales_assignment_active_customer``, ``ix_products_sub_category_lower``,
``ix_orders_placed_at``) are KEPT: they are now declared in the models'
``__table_args__`` rather than dropped here.

After this runs, ``alembic upgrade head && alembic check`` reports no changes.
``downgrade()`` restores every default and constraint verbatim.

Revision ID: 0019_align_server_defaults
Revises: 0018_job_outbox
Create Date: 2026-08-02
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019_align_server_defaults"
down_revision: str | Sequence[str] | None = "0018_job_outbox"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'is_default_shipping',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('addresses', 'is_default_billing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_settings', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('attendance_records', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cart_items', 'currency_snapshot',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('carts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_categories_slug', 'categories', type_='unique')
    op.alter_column('cms_blocks', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cms_blocks', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cms_pages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('compare_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('coupons', 'min_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('coupons', 'used_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_coupons_code', 'coupons', type_='unique')
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enquiries', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enquiry_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enquiry_messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('enquiry_status_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('feature_flags', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('holidays', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('holidays', 'kind',
               existing_type=sa.VARCHAR(length=40),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_holidays_day', 'holidays', type_='unique')
    op.alter_column('job_outbox', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_outbox', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('kyc_documents', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_balances', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_balances', 'allocated_days',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_balances', 'used_days',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_requests', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_types', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('leave_types', 'annual_quota_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('message_reads', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('placed', 'confirmed', 'packed', 'dispatched', 'out_for_delivery', 'delivered', 'cancelled', 'refunded', 'payment_failed', name='order_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'discount_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'gst_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'shipping_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'cod_pending', 'authorized', 'captured', 'failed', 'refunded', 'partial_refund', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_orders_order_number', 'orders', type_='unique')
    op.alter_column('otp_codes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'cod_pending', 'authorized', 'captured', 'failed', 'refunded', 'partial_refund', name='payment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_payments_gateway_payment_id', 'payments', type_='unique')
    op.alter_column('payroll_runs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payslips', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payslips', 'allowances_paise',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payslips', 'deductions_paise',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pincodes', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_prices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_variants', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_variants', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'schedule',
               existing_type=postgresql.ENUM('NONE', 'H', 'H1', 'X', name='schedule_class'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'stock_status',
               existing_type=postgresql.ENUM('in_stock', 'low_stock', 'out_of_stock', 'discontinued', name='stock_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'gst_rate_pct',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_products_slug', 'products', type_='unique')
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='refund_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('refunds', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_assignments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales_targets', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('pending', 'in_transit', 'out_for_delivery', 'delivered', 'returned', name='shipment_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_levels', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_profiles', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('verification_requests', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('warehouses', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wishlist_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('warehouses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('verification_requests', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('user_profiles', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('stock_levels', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('stock_ledger', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=postgresql.ENUM('pending', 'in_transit', 'out_for_delivery', 'delivered', 'returned', name='shipment_status'),
               server_default=sa.text("'pending'::shipment_status"),
               existing_nullable=False)
    op.alter_column('sales_targets', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('sales_assignments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('refunds', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('refunds', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='refund_status'),
               server_default=sa.text("'pending'::refund_status"),
               existing_nullable=False)
    op.create_unique_constraint('uq_products_slug', 'products', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('products', 'specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('products', 'reviews_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('products', 'gst_rate_pct',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('12'),
               existing_nullable=False)
    op.alter_column('products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('products', 'stock_status',
               existing_type=postgresql.ENUM('in_stock', 'low_stock', 'out_of_stock', 'discontinued', name='stock_status'),
               server_default=sa.text("'in_stock'::stock_status"),
               existing_nullable=False)
    op.alter_column('products', 'schedule',
               existing_type=postgresql.ENUM('NONE', 'H', 'H1', 'X', name='schedule_class'),
               server_default=sa.text("'NONE'::schedule_class"),
               existing_nullable=False)
    op.alter_column('product_variants', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('product_variants', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('product_prices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('product_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('pincodes', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'india_post'::character varying"),
               existing_nullable=False)
    op.alter_column('payslips', 'deductions_paise',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('payslips', 'allowances_paise',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('payslips', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('payroll_runs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_payments_gateway_payment_id', 'payments', ['gateway_payment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payments', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'cod_pending', 'authorized', 'captured', 'failed', 'refunded', 'partial_refund', name='payment_status'),
               server_default=sa.text("'pending'::payment_status"),
               existing_nullable=False)
    op.alter_column('otp_codes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_orders_order_number', 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'cod_pending', 'authorized', 'captured', 'failed', 'refunded', 'partial_refund', name='payment_status'),
               server_default=sa.text("'pending'::payment_status"),
               existing_nullable=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('orders', 'gst_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('orders', 'discount_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('placed', 'confirmed', 'packed', 'dispatched', 'out_for_delivery', 'delivered', 'cancelled', 'refunded', 'payment_failed', name='order_status'),
               server_default=sa.text("'placed'::order_status"),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('message_reads', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('leave_types', 'annual_quota_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('leave_types', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('leave_requests', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('leave_balances', 'used_days',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('leave_balances', 'allocated_days',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('leave_balances', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('kyc_documents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('job_outbox', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('job_outbox', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_holidays_day', 'holidays', ['day'], postgresql_nulls_not_distinct=False)
    op.alter_column('holidays', 'kind',
               existing_type=sa.VARCHAR(length=40),
               server_default=sa.text("'national'::character varying"),
               existing_nullable=False)
    op.alter_column('holidays', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('feature_flags', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('enquiry_status_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('enquiry_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('enquiry_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('enquiries', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('employees', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_coupons_code', 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('coupons', 'used_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('coupons', 'min_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('compare_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('cms_pages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('cms_blocks', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('cms_blocks', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_unique_constraint('uq_categories_slug', 'categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('carts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('cart_items', 'currency_snapshot',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'INR'::character varying"),
               existing_nullable=False)
    op.alter_column('audit_log', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('attendance_records', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('app_settings', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('addresses', 'is_default_billing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('addresses', 'is_default_shipping',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
